name: Streamlit CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r BMI/requirements.txt

    - name: Run tests
      run: |
        streamlit run BMI/bmi_calculator.py --server.headless true --browser.serverAddress 0.0.0.0 --browser.gatherUsageStats false

    - name: Deploy to Streamlit Sharing
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: streamlit deploy bmi_calculator.py --app "your-streamlit-app-name"
      env:
        STREAMLIT_SHARE_API_TOKEN: ${{ secrets.STREAMLIT_SHARE_API_TOKEN }}
